[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000"
    Content-Security-Policy = '''
	  default-src=none,
	  img-src=self,
	  script-src=self,
	  style-src=self,
	  frame-ancestors,
	  form-action=none,
	  base-uri=self'''
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"